# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HaystackArmy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HaystackArmy
 
  #              -----   SDWEB Image     --------
  pod 'SDWebImage'
  #                     -----   Keyboard management  --------
  pod 'IQKeyboardManagerSwift'
  
  #                     -----  Almofire for Api hittng  --------
  pod 'Alamofire', '~> 4.9.1’
  
  #                     ----  Progress loader  --------
  pod 'MBProgressHUD'
  
    #                     ----  json object mapper  --------
  pod 'ObjectMapper'
  
  #                     ----  crashes  --------

#  pod 'Fabric'
#  pod 'Crashlytics'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
   
  
  pod 'GooglePlaces'
  
  pod 'GoogleMaps'
#  pod 'GooglePlacePicker'


  target 'HaystackArmyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HaystackArmyUITests' do
    # Pods for testing
  end

end
